//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMaP.Resources.Pages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Assessment {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Assessment() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PMaP.Resources.Pages.Assessment", typeof(Assessment).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contratos.
        /// </summary>
        public static string Contracts {
            get {
                return ResourceManager.GetString("Contracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deudores.
        /// </summary>
        public static string Debtors {
            get {
                return ResourceManager.GetString("Debtors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiadores.
        /// </summary>
        public static string Guarantors {
            get {
                return ResourceManager.GetString("Guarantors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secured OB.
        /// </summary>
        public static string Secured_OB {
            get {
                return ResourceManager.GetString("Secured OB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio Secured.
        /// </summary>
        public static string Secured_Price {
            get {
                return ResourceManager.GetString("Secured Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total OB.
        /// </summary>
        public static string Total_OB {
            get {
                return ResourceManager.GetString("Total OB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsecured OB.
        /// </summary>
        public static string Unsecured_OB {
            get {
                return ResourceManager.GetString("Unsecured OB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio Unsecured.
        /// </summary>
        public static string Unsecured_Price {
            get {
                return ResourceManager.GetString("Unsecured Price", resourceCulture);
            }
        }
    }
}
