//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMaP.Resources.Pages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PMaP.Resources.Pages.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Año de adquisición.
        /// </summary>
        public static string AcquisitionYear {
            get {
                return ResourceManager.GetString("AcquisitionYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entidad de cesión.
        /// </summary>
        public static string AssignmentEntity {
            get {
                return ResourceManager.GetString("AssignmentEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de deuda.
        /// </summary>
        public static string DebtType {
            get {
                return ResourceManager.GetString("DebtType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Características generales.
        /// </summary>
        public static string GeneralCharacteristics {
            get {
                return ResourceManager.GetString("GeneralCharacteristics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Página principal.
        /// </summary>
        public static string lblHome {
            get {
                return ResourceManager.GetString("lblHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor nominal.
        /// </summary>
        public static string NominalValue {
            get {
                return ResourceManager.GetString("NominalValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portfolio.
        /// </summary>
        public static string Portfolio {
            get {
                return ResourceManager.GetString("Portfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composición de la cartera.
        /// </summary>
        public static string PortfolioComposition {
            get {
                return ResourceManager.GetString("PortfolioComposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio secured.
        /// </summary>
        public static string PriceSecured {
            get {
                return ResourceManager.GetString("PriceSecured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secured.
        /// </summary>
        public static string Secured {
            get {
                return ResourceManager.GetString("Secured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subportfolio.
        /// </summary>
        public static string Subportfolio {
            get {
                return ResourceManager.GetString("Subportfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsecured.
        /// </summary>
        public static string Unsecured {
            get {
                return ResourceManager.GetString("Unsecured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio unsecured.
        /// </summary>
        public static string UnsecuredPrice {
            get {
                return ResourceManager.GetString("UnsecuredPrice", resourceCulture);
            }
        }
    }
}
