//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMaP.Resources.Pages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PortfolioProgress {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PortfolioProgress() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PMaP.Resources.Pages.PortfolioProgress", typeof(PortfolioProgress).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calcular.
        /// </summary>
        public static string Calcular {
            get {
                return ResourceManager.GetString("Calcular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capital pendiente.
        /// </summary>
        public static string CapitalPendiente {
            get {
                return ResourceManager.GetString("CapitalPendiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capital vencido.
        /// </summary>
        public static string CapitalVencido {
            get {
                return ResourceManager.GetString("CapitalVencido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartera.
        /// </summary>
        public static string Cartera {
            get {
                return ResourceManager.GetString("Cartera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        public static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concursos.
        /// </summary>
        public static string Concursos {
            get {
                return ResourceManager.GetString("Concursos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contratos.
        /// </summary>
        public static string Contratos {
            get {
                return ResourceManager.GetString("Contratos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuotas impagadas.
        /// </summary>
        public static string CuotasImpagadas {
            get {
                return ResourceManager.GetString("CuotasImpagadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuotas pendientes.
        /// </summary>
        public static string CuotasPendientes {
            get {
                return ResourceManager.GetString("CuotasPendientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataTape.
        /// </summary>
        public static string DataTape {
            get {
                return ResourceManager.GetString("DataTape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divisa.
        /// </summary>
        public static string Divisa {
            get {
                return ResourceManager.GetString("Divisa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado performing.
        /// </summary>
        public static string EstadoPerforming {
            get {
                return ResourceManager.GetString("EstadoPerforming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evolución de la Cartera.
        /// </summary>
        public static string EvolucionDeLaCartera {
            get {
                return ResourceManager.GetString("EvolucionDeLaCartera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F. DataTape.
        /// </summary>
        public static string FDataTape {
            get {
                return ResourceManager.GetString("FDataTape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha novación.
        /// </summary>
        public static string FechaNovacion {
            get {
                return ResourceManager.GetString("FechaNovacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F. Proceso.
        /// </summary>
        public static string FProceso {
            get {
                return ResourceManager.GetString("FProceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Contrato.
        /// </summary>
        public static string IDContrato {
            get {
                return ResourceManager.GetString("IDContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Titular principal.
        /// </summary>
        public static string IDTitularPrincipal {
            get {
                return ResourceManager.GetString("IDTitularPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información Contratos.
        /// </summary>
        public static string InformacionContratos {
            get {
                return ResourceManager.GetString("InformacionContratos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información judicial y concursal.
        /// </summary>
        public static string InformacionJudicialYConcursal {
            get {
                return ResourceManager.GetString("InformacionJudicialYConcursal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información Participantes.
        /// </summary>
        public static string InformacionParticipantes {
            get {
                return ResourceManager.GetString("InformacionParticipantes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intereses de demora.
        /// </summary>
        public static string InteresesDeDemora {
            get {
                return ResourceManager.GetString("InteresesDeDemora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intereses ordinarios.
        /// </summary>
        public static string InteresesOrdinarios {
            get {
                return ResourceManager.GetString("InteresesOrdinarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LTV actual.
        /// </summary>
        public static string LTVActual {
            get {
                return ResourceManager.GetString("LTVActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº Cambios concursales.
        /// </summary>
        public static string NoCambiosConcursales {
            get {
                return ResourceManager.GetString("NoCambiosConcursales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº Cambios judiciales.
        /// </summary>
        public static string NoCambiosJudiciales {
            get {
                return ResourceManager.GetString("NoCambiosJudiciales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº Contratos eliminados.
        /// </summary>
        public static string NoContratosEliminados {
            get {
                return ResourceManager.GetString("NoContratosEliminados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº Contratos nuevos.
        /// </summary>
        public static string NoContratosNuevos {
            get {
                return ResourceManager.GetString("NoContratosNuevos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº fiadores.
        /// </summary>
        public static string NoFiadores {
            get {
                return ResourceManager.GetString("NoFiadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº participantes.
        /// </summary>
        public static string NoParticipantes {
            get {
                return ResourceManager.GetString("NoParticipantes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº Participantes eliminados.
        /// </summary>
        public static string NoParticipantesEliminados {
            get {
                return ResourceManager.GetString("NoParticipantesEliminados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº Participantes nuevos.
        /// </summary>
        public static string NoParticipantesNuevos {
            get {
                return ResourceManager.GetString("NoParticipantesNuevos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novación.
        /// </summary>
        public static string Novacion {
            get {
                return ResourceManager.GetString("Novacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participantes.
        /// </summary>
        public static string Participantes {
            get {
                return ResourceManager.GetString("Participantes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portfolio.
        /// </summary>
        public static string Portfolio {
            get {
                return ResourceManager.GetString("Portfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedimientos judiciales.
        /// </summary>
        public static string ProcedimientosJudiciales {
            get {
                return ResourceManager.GetString("ProcedimientosJudiciales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subporfolio.
        /// </summary>
        public static string Subporfolio {
            get {
                return ResourceManager.GetString("Subporfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo deuda.
        /// </summary>
        public static string TipoDeuda {
            get {
                return ResourceManager.GetString("TipoDeuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total OB.
        /// </summary>
        public static string TotalOB {
            get {
                return ResourceManager.GetString("TotalOB", resourceCulture);
            }
        }
    }
}
