//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMaP.Common.General {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextMenus {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextMenus() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PMaP.Common.General.TextMenus", typeof(TextMenus).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizaciones.
        /// </summary>
        public static string itemActualizaciones {
            get {
                return ResourceManager.GetString("itemActualizaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concursos / Adjudicaciones.
        /// </summary>
        public static string itemActualizacionesConcursosAdjudicaciones {
            get {
                return ResourceManager.GetString("itemActualizacionesConcursosAdjudicaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participantes.
        /// </summary>
        public static string itemActualizacionesParticipantes {
            get {
                return ResourceManager.GetString("itemActualizacionesParticipantes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedimientos judiciales.
        /// </summary>
        public static string itemActualizacionesProcedimientosJudiciales {
            get {
                return ResourceManager.GetString("itemActualizacionesProcedimientosJudiciales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recuperaciones deuda.
        /// </summary>
        public static string itemActualizacionesRecuperacionesDeuda {
            get {
                return ResourceManager.GetString("itemActualizacionesRecuperacionesDeuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alta de carteras.
        /// </summary>
        public static string itemAltaDeCarteras {
            get {
                return ResourceManager.GetString("itemAltaDeCarteras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificados.
        /// </summary>
        public static string itemCertificados {
            get {
                return ResourceManager.GetString("itemCertificados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alta plantillas.
        /// </summary>
        public static string itemCertificadosAltaPlantillas {
            get {
                return ResourceManager.GetString("itemCertificadosAltaPlantillas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generación de certificados.
        /// </summary>
        public static string itemCertificadosGeneracionDeCertificados {
            get {
                return ResourceManager.GetString("itemCertificadosGeneracionDeCertificados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generación de formularios.
        /// </summary>
        public static string itemCertificadosGeneracionDeFormularios {
            get {
                return ResourceManager.GetString("itemCertificadosGeneracionDeFormularios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comunicados.
        /// </summary>
        public static string itemComunicados {
            get {
                return ResourceManager.GetString("itemComunicados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataTapes.
        /// </summary>
        public static string itemDataTapes {
            get {
                return ResourceManager.GetString("itemDataTapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colaterales.
        /// </summary>
        public static string itemDataTapesColaterals {
            get {
                return ResourceManager.GetString("itemDataTapesColaterals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contratos.
        /// </summary>
        public static string itemDataTapesContracts {
            get {
                return ResourceManager.GetString("itemDataTapesContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insolvencias.
        /// </summary>
        public static string itemDataTapesInsolvencies {
            get {
                return ResourceManager.GetString("itemDataTapesInsolvencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liens.
        /// </summary>
        public static string itemDataTapesLiens {
            get {
                return ResourceManager.GetString("itemDataTapesLiens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novations.
        /// </summary>
        public static string itemDataTapesNovations {
            get {
                return ResourceManager.GetString("itemDataTapesNovations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participantes.
        /// </summary>
        public static string itemDataTapesParticipants {
            get {
                return ResourceManager.GetString("itemDataTapesParticipants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precios.
        /// </summary>
        public static string itemDataTapesPrices {
            get {
                return ResourceManager.GetString("itemDataTapesPrices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedimientos.
        /// </summary>
        public static string itemDataTapesProcedures {
            get {
                return ResourceManager.GetString("itemDataTapesProcedures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generación de datatapes.
        /// </summary>
        public static string itemGeneracionDeDatatapes {
            get {
                return ResourceManager.GetString("itemGeneracionDeDatatapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        public static string itemHome {
            get {
                return ResourceManager.GetString("itemHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evolución de la cartera.
        /// </summary>
        public static string itemPortfolioEvolution {
            get {
                return ResourceManager.GetString("itemPortfolioEvolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portfolios.
        /// </summary>
        public static string itemPortfolios {
            get {
                return ResourceManager.GetString("itemPortfolios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valoración de carteras.
        /// </summary>
        public static string itemPortfolioValuation {
            get {
                return ResourceManager.GetString("itemPortfolioValuation", resourceCulture);
            }
        }
    }
}
