//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMaP.Resources.Pages.PortfolioEvaluation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DetailsTable {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DetailsTable() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PMaP.Resources.Pages.PortfolioEvaluation.DetailsTable", typeof(DetailsTable).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entidad de cesión.
        /// </summary>
        public static string AssignmentEntity {
            get {
                return ResourceManager.GetString("AssignmentEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saldo (OB).
        /// </summary>
        public static string BalanceOB {
            get {
                return ResourceManager.GetString("BalanceOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrato.
        /// </summary>
        public static string Contract {
            get {
                return ResourceManager.GetString("Contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha primer imapago.
        /// </summary>
        public static string FirstUnpaidInstallmentDate {
            get {
                return ResourceManager.GetString("FirstUnpaidInstallmentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Judicializado.
        /// </summary>
        public static string JudicialProcess {
            get {
                return ResourceManager.GetString("JudicialProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha vencimiento.
        /// </summary>
        public static string MaturityDate {
            get {
                return ResourceManager.GetString("MaturityDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capital vencido.
        /// </summary>
        public static string MaturityPrincipalBalance {
            get {
                return ResourceManager.GetString("MaturityPrincipalBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº Fiadores.
        /// </summary>
        public static string NoGuarantors {
            get {
                return ResourceManager.GetString("NoGuarantors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origen.
        /// </summary>
        public static string Origin {
            get {
                return ResourceManager.GetString("Origin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha firma.
        /// </summary>
        public static string OriginationDate {
            get {
                return ResourceManager.GetString("OriginationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capital pendiente.
        /// </summary>
        public static string OutstandingPrincipalBalance {
            get {
                return ResourceManager.GetString("OutstandingPrincipalBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titular.
        /// </summary>
        public static string Participant {
            get {
                return ResourceManager.GetString("Participant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portfolio.
        /// </summary>
        public static string Portfolio {
            get {
                return ResourceManager.GetString("Portfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo procedimiento judicial.
        /// </summary>
        public static string TypeOfJudicialProcedure {
            get {
                return ResourceManager.GetString("TypeOfJudicialProcedure", resourceCulture);
            }
        }
    }
}
