//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMaP.Resources.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NavMenu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NavMenu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PMaP.Resources.Shared.NavMenu", typeof(NavMenu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizaciones.
        /// </summary>
        public static string Actualization {
            get {
                return ResourceManager.GetString("Actualization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generación de certificados.
        /// </summary>
        public static string CertificateGeneration {
            get {
                return ResourceManager.GetString("CertificateGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificados.
        /// </summary>
        public static string Certificates {
            get {
                return ResourceManager.GetString("Certificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colaterales.
        /// </summary>
        public static string Colaterals {
            get {
                return ResourceManager.GetString("Colaterals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concursos / Adjudicaciones.
        /// </summary>
        public static string ConcourseAdjudication {
            get {
                return ResourceManager.GetString("ConcourseAdjudication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contratos.
        /// </summary>
        public static string Contracts {
            get {
                return ResourceManager.GetString("Contracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataTapes.
        /// </summary>
        public static string DataTapes {
            get {
                return ResourceManager.GetString("DataTapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participantes.
        /// </summary>
        public static string DataTapesParticipants {
            get {
                return ResourceManager.GetString("DataTapesParticipants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recuperaciones deuda.
        /// </summary>
        public static string DebtRecoveries {
            get {
                return ResourceManager.GetString("DebtRecoveries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generación de formularios.
        /// </summary>
        public static string FormGeneration {
            get {
                return ResourceManager.GetString("FormGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generación de cintas de datos.
        /// </summary>
        public static string GenerationOfDatatapes {
            get {
                return ResourceManager.GetString("GenerationOfDatatapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alta plantillas.
        /// </summary>
        public static string High_templates {
            get {
                return ResourceManager.GetString("High templates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insolvencias.
        /// </summary>
        public static string Insolvencies {
            get {
                return ResourceManager.GetString("Insolvencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedimientos judiciales.
        /// </summary>
        public static string JudicialProceedings {
            get {
                return ResourceManager.GetString("JudicialProceedings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravámenes.
        /// </summary>
        public static string Liens {
            get {
                return ResourceManager.GetString("Liens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificaciones.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novations.
        /// </summary>
        public static string Novations {
            get {
                return ResourceManager.GetString("Novations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participantes.
        /// </summary>
        public static string Participants {
            get {
                return ResourceManager.GetString("Participants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valoración de carteras.
        /// </summary>
        public static string PortfolioEvaluation {
            get {
                return ResourceManager.GetString("PortfolioEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mercado de cartera.
        /// </summary>
        public static string PortfolioMarket {
            get {
                return ResourceManager.GetString("PortfolioMarket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evolución de la cartera.
        /// </summary>
        public static string PortfolioProgress {
            get {
                return ResourceManager.GetString("PortfolioProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alta de carteras.
        /// </summary>
        public static string PortfolioRegistration {
            get {
                return ResourceManager.GetString("PortfolioRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portfolios.
        /// </summary>
        public static string Portfolios {
            get {
                return ResourceManager.GetString("Portfolios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precios.
        /// </summary>
        public static string Prices {
            get {
                return ResourceManager.GetString("Prices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedimientos.
        /// </summary>
        public static string Procedures {
            get {
                return ResourceManager.GetString("Procedures", resourceCulture);
            }
        }
    }
}
