//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMaP.Resources.Pages.Portfolios {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ContractsTable {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContractsTable() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PMaP.Resources.Pages.Portfolios.ContractsTable", typeof(ContractsTable).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situacion contable.
        /// </summary>
        public static string AccountingSituation {
            get {
                return ResourceManager.GetString("AccountingSituation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Contrato.
        /// </summary>
        public static string ContractID {
            get {
                return ResourceManager.GetString("ContractID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipología.
        /// </summary>
        public static string ContractType {
            get {
                return ResourceManager.GetString("ContractType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divisa.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo deuda.
        /// </summary>
        public static string DebtType {
            get {
                return ResourceManager.GetString("DebtType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha fallido.
        /// </summary>
        public static string DefaultDate {
            get {
                return ResourceManager.GetString("DefaultDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intereses de demora.
        /// </summary>
        public static string DefaultInterests {
            get {
                return ResourceManager.GetString("DefaultInterests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vencimiento anticipado.
        /// </summary>
        public static string EarlyMaturity {
            get {
                return ResourceManager.GetString("EarlyMaturity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha vencimiento anticipado.
        /// </summary>
        public static string EarlyMaturityDate {
            get {
                return ResourceManager.GetString("EarlyMaturityDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha primer imapago.
        /// </summary>
        public static string FirstUnpaidInstalmentDate {
            get {
                return ResourceManager.GetString("FirstUnpaidInstalmentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concurso.
        /// </summary>
        public static string Insolvency {
            get {
                return ResourceManager.GetString("Insolvency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Judicializado.
        /// </summary>
        public static string JudicialProcess {
            get {
                return ResourceManager.GetString("JudicialProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concursado.
        /// </summary>
        public static string LegalProcess {
            get {
                return ResourceManager.GetString("LegalProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LTV actual.
        /// </summary>
        public static string LTVOriginal {
            get {
                return ResourceManager.GetString("LTVOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Titular principal.
        /// </summary>
        public static string MainParticipantID {
            get {
                return ResourceManager.GetString("MainParticipantID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha vencimiento.
        /// </summary>
        public static string MaturityDate {
            get {
                return ResourceManager.GetString("MaturityDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capital vencido.
        /// </summary>
        public static string MaturityPrincipalBalance {
            get {
                return ResourceManager.GetString("MaturityPrincipalBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novación.
        /// </summary>
        public static string Novation {
            get {
                return ResourceManager.GetString("Novation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha novación.
        /// </summary>
        public static string NovationDate {
            get {
                return ResourceManager.GetString("NovationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº fiadores.
        /// </summary>
        public static string NumGuarantors {
            get {
                return ResourceManager.GetString("NumGuarantors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº participantes.
        /// </summary>
        public static string NumParticipants {
            get {
                return ResourceManager.GetString("NumParticipants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intereses ordinarios.
        /// </summary>
        public static string OrdinaryInterests {
            get {
                return ResourceManager.GetString("OrdinaryInterests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banco procedencia.
        /// </summary>
        public static string OriginalEntity {
            get {
                return ResourceManager.GetString("OriginalEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha firma.
        /// </summary>
        public static string OriginationDate {
            get {
                return ResourceManager.GetString("OriginationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuotas pendientes.
        /// </summary>
        public static string OutstandingInstalments {
            get {
                return ResourceManager.GetString("OutstandingInstalments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capital pendiente.
        /// </summary>
        public static string OutstandingPrincipalBalance {
            get {
                return ResourceManager.GetString("OutstandingPrincipalBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Sindicación.
        /// </summary>
        public static string PercentOfSyndication {
            get {
                return ResourceManager.GetString("PercentOfSyndication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado performing.
        /// </summary>
        public static string PerformingStatus {
            get {
                return ResourceManager.GetString("PerformingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portfolio.
        /// </summary>
        public static string Portfolio {
            get {
                return ResourceManager.GetString("Portfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceso Judicial.
        /// </summary>
        public static string ProceedingType {
            get {
                return ResourceManager.GetString("ProceedingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha proceso.
        /// </summary>
        public static string ProcessDate {
            get {
                return ResourceManager.GetString("ProcessDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjudicación.
        /// </summary>
        public static string REO {
            get {
                return ResourceManager.GetString("REO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importe Adjudicación.
        /// </summary>
        public static string REOAmount {
            get {
                return ResourceManager.GetString("REOAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titulizado.
        /// </summary>
        public static string Securitized {
            get {
                return ResourceManager.GetString("Securitized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num Titulizado.
        /// </summary>
        public static string SecurityNumber {
            get {
                return ResourceManager.GetString("SecurityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subportfolio.
        /// </summary>
        public static string Subportfolio {
            get {
                return ResourceManager.GetString("Subportfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sindicado.
        /// </summary>
        public static string Syndicated {
            get {
                return ResourceManager.GetString("Syndicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total OB.
        /// </summary>
        public static string TotalAmountOB {
            get {
                return ResourceManager.GetString("TotalAmountOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuotas impagadas.
        /// </summary>
        public static string UnpaidInstalments {
            get {
                return ResourceManager.GetString("UnpaidInstalments", resourceCulture);
            }
        }
    }
}
