//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMaP.Resources.Pages.Portfolios {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Portfolios {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Portfolios() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PMaP.Resources.Pages.Portfolios.Portfolios", typeof(Portfolios).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir.
        /// </summary>
        public static string AddContracts {
            get {
                return ResourceManager.GetString("AddContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valoración.
        /// </summary>
        public static string Assessment {
            get {
                return ResourceManager.GetString("Assessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificado.
        /// </summary>
        public static string Certificate {
            get {
                return ResourceManager.GetString("Certificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Características.
        /// </summary>
        public static string Characteristics {
            get {
                return ResourceManager.GetString("Characteristics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colaterals.
        /// </summary>
        public static string Collaterals {
            get {
                return ResourceManager.GetString("Collaterals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comunicaciones.
        /// </summary>
        public static string Communications {
            get {
                return ResourceManager.GetString("Communications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrato.
        /// </summary>
        public static string Contract {
            get {
                return ResourceManager.GetString("Contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contratos.
        /// </summary>
        public static string Contracts {
            get {
                return ResourceManager.GetString("Contracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha alta / actualización.
        /// </summary>
        public static string DateAddedUpdate {
            get {
                return ResourceManager.GetString("DateAddedUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descarte.
        /// </summary>
        public static string Discard {
            get {
                return ResourceManager.GetString("Discard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F. Closing.
        /// </summary>
        public static string FClosing {
            get {
                return ResourceManager.GetString("FClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F. Cut off.
        /// </summary>
        public static string FCutOff {
            get {
                return ResourceManager.GetString("FCutOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F. Singning.
        /// </summary>
        public static string FSingning {
            get {
                return ResourceManager.GetString("FSingning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titular.
        /// </summary>
        public static string Holder {
            get {
                return ResourceManager.GetString("Holder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concursos.
        /// </summary>
        public static string Insolvencies {
            get {
                return ResourceManager.GetString("Insolvencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inversor.
        /// </summary>
        public static string Investor {
            get {
                return ResourceManager.GetString("Investor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portfolios.
        /// </summary>
        public static string lblPortfolios {
            get {
                return ResourceManager.GetString("lblPortfolios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liens.
        /// </summary>
        public static string Liens {
            get {
                return ResourceManager.GetString("Liens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novaciones.
        /// </summary>
        public static string Novations {
            get {
                return ResourceManager.GetString("Novations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OB Closing.
        /// </summary>
        public static string OBClosing {
            get {
                return ResourceManager.GetString("OBClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OB Cut off.
        /// </summary>
        public static string OBCutOff {
            get {
                return ResourceManager.GetString("OBCutOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OB Singning.
        /// </summary>
        public static string OBSingning {
            get {
                return ResourceManager.GetString("OBSingning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo operación.
        /// </summary>
        public static string OperationType {
            get {
                return ResourceManager.GetString("OperationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participantes.
        /// </summary>
        public static string Participants {
            get {
                return ResourceManager.GetString("Participants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portfolio.
        /// </summary>
        public static string Portfolio {
            get {
                return ResourceManager.GetString("Portfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Judicial.
        /// </summary>
        public static string Procedures {
            get {
                return ResourceManager.GetString("Procedures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situación.
        /// </summary>
        public static string Situation {
            get {
                return ResourceManager.GetString("Situation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subporfolio.
        /// </summary>
        public static string Subporfolio {
            get {
                return ResourceManager.GetString("Subporfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resumen.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
    }
}
