//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMaP.Resources.Pages.Portfolios {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProceduresTable {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProceduresTable() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PMaP.Resources.Pages.Portfolios.ProceduresTable", typeof(ProceduresTable).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importe reclamado.
        /// </summary>
        public static string AmountClaimed {
            get {
                return ResourceManager.GetString("AmountClaimed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Contrato.
        /// </summary>
        public static string ContractId {
            get {
                return ResourceManager.GetString("ContractId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Juzgado.
        /// </summary>
        public static string Court {
            get {
                return ResourceManager.GetString("Court", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localidad.
        /// </summary>
        public static string CourtCity {
            get {
                return ResourceManager.GetString("CourtCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Juzgado.
        /// </summary>
        public static string CourtNumber {
            get {
                return ResourceManager.GetString("CourtNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero de auto.
        /// </summary>
        public static string CourtProcedureNumber {
            get {
                return ResourceManager.GetString("CourtProcedureNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provincia.
        /// </summary>
        public static string CourtProvince {
            get {
                return ResourceManager.GetString("CourtProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importe costas.
        /// </summary>
        public static string JudicialCostAmount {
            get {
                return ResourceManager.GetString("JudicialCostAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre Despacho.
        /// </summary>
        public static string LawFirm {
            get {
                return ResourceManager.GetString("LawFirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha admisión demanda.
        /// </summary>
        public static string LawsuitDate {
            get {
                return ResourceManager.GetString("LawsuitDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo Abogado.
        /// </summary>
        public static string LawyerMail {
            get {
                return ResourceManager.GetString("LawyerMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abogado.
        /// </summary>
        public static string LawyerName {
            get {
                return ResourceManager.GetString("LawyerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono Abogado.
        /// </summary>
        public static string LawyerPhoneNumber {
            get {
                return ResourceManager.GetString("LawyerPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo proceso.
        /// </summary>
        public static string ProcedureType {
            get {
                return ResourceManager.GetString("ProcedureType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Procedimiento.
        /// </summary>
        public static string ProceedingType {
            get {
                return ResourceManager.GetString("ProceedingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha proceso.
        /// </summary>
        public static string ProcessDate {
            get {
                return ResourceManager.GetString("ProcessDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo Procurador.
        /// </summary>
        public static string SolicitorMail {
            get {
                return ResourceManager.GetString("SolicitorMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procurador.
        /// </summary>
        public static string SolicitorName {
            get {
                return ResourceManager.GetString("SolicitorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono Procurador.
        /// </summary>
        public static string SolicitorPhoneNumber {
            get {
                return ResourceManager.GetString("SolicitorPhoneNumber", resourceCulture);
            }
        }
    }
}
