//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMaP.Resources.Pages.Certificates {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CertificateGeneration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CertificateGeneration() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PMaP.Resources.Pages.Certificates.CertificateGeneration", typeof(CertificateGeneration).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apoderado.
        /// </summary>
        public static string Apoderado {
            get {
                return ResourceManager.GetString("Apoderado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificado.
        /// </summary>
        public static string Certificado {
            get {
                return ResourceManager.GetString("Certificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificado de cesión.
        /// </summary>
        public static string CertificadoDeCesion {
            get {
                return ResourceManager.GetString("CertificadoDeCesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificado de saldo.
        /// </summary>
        public static string CertificadoDeSaldo {
            get {
                return ResourceManager.GetString("CertificadoDeSaldo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificados.
        /// </summary>
        public static string Certificados {
            get {
                return ResourceManager.GetString("Certificados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cesión - Garantía hipotecaria.
        /// </summary>
        public static string CesionGarantiaHipotecaria {
            get {
                return ResourceManager.GetString("CesionGarantiaHipotecaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cesión - Póliza.
        /// </summary>
        public static string CesionPoliza {
            get {
                return ResourceManager.GetString("CesionPoliza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cesión - Sin desglose de deuda.
        /// </summary>
        public static string CesionSinDesgloseDeDeuda {
            get {
                return ResourceManager.GetString("CesionSinDesgloseDeDeuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrato.
        /// </summary>
        public static string Contrato {
            get {
                return ResourceManager.GetString("Contrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos básicos.
        /// </summary>
        public static string DatosBasicos {
            get {
                return ResourceManager.GetString("DatosBasicos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interviniente.
        /// </summary>
        public static string Interviniente {
            get {
                return ResourceManager.GetString("Interviniente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inversor.
        /// </summary>
        public static string Inversor {
            get {
                return ResourceManager.GetString("Inversor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portfolio.
        /// </summary>
        public static string Portfolio {
            get {
                return ResourceManager.GetString("Portfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saldo - Con desglose de deuda.
        /// </summary>
        public static string SaldoConDesgloseDeDeuda {
            get {
                return ResourceManager.GetString("SaldoConDesgloseDeDeuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asegurado.
        /// </summary>
        public static string Secured {
            get {
                return ResourceManager.GetString("Secured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar.
        /// </summary>
        public static string Seleccionar {
            get {
                return ResourceManager.GetString("Seleccionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selección del Certificado.
        /// </summary>
        public static string SeleccionDelCertificado {
            get {
                return ResourceManager.GetString("SeleccionDelCertificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subporfolio.
        /// </summary>
        public static string Subporfolio {
            get {
                return ResourceManager.GetString("Subporfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtipo de certificado.
        /// </summary>
        public static string SubtipoDeCertificado {
            get {
                return ResourceManager.GetString("SubtipoDeCertificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de deuda.
        /// </summary>
        public static string TipoDeDeuda {
            get {
                return ResourceManager.GetString("TipoDeDeuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo deuda.
        /// </summary>
        public static string TipoDeuda {
            get {
                return ResourceManager.GetString("TipoDeuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo interviniente.
        /// </summary>
        public static string TipoInterviniente {
            get {
                return ResourceManager.GetString("TipoInterviniente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inseguro.
        /// </summary>
        public static string Unsecured {
            get {
                return ResourceManager.GetString("Unsecured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizar.
        /// </summary>
        public static string Visualizar {
            get {
                return ResourceManager.GetString("Visualizar", resourceCulture);
            }
        }
    }
}
