//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMaP.Resources.Pages.Certificates {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FormGeneration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormGeneration() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PMaP.Resources.Pages.Certificates.FormGeneration", typeof(FormGeneration).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apoderado.
        /// </summary>
        public static string Apoderado {
            get {
                return ResourceManager.GetString("Apoderado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificados.
        /// </summary>
        public static string Certificados {
            get {
                return ResourceManager.GetString("Certificados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CIF.
        /// </summary>
        public static string CIF {
            get {
                return ResourceManager.GetString("CIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear plantilla nueva.
        /// </summary>
        public static string CrearPlantillaNueva {
            get {
                return ResourceManager.GetString("CrearPlantillaNueva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descargar certificados.
        /// </summary>
        public static string DescargarCertificados {
            get {
                return ResourceManager.GetString("DescargarCertificados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección.
        /// </summary>
        public static string Direccion {
            get {
                return ResourceManager.GetString("Direccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DNI apoderado.
        /// </summary>
        public static string DNIApoderado {
            get {
                return ResourceManager.GetString("DNIApoderado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de la venta.
        /// </summary>
        public static string FechaDeLaVenta {
            get {
                return ResourceManager.GetString("FechaDeLaVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generar plantilla.
        /// </summary>
        public static string GenerarPlantilla {
            get {
                return ResourceManager.GetString("GenerarPlantilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string Guardar {
            get {
                return ResourceManager.GetString("Guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información del notario.
        /// </summary>
        public static string InformacionDelNotario {
            get {
                return ResourceManager.GetString("InformacionDelNotario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ejemplo: Que conforme a la escritura de cesión de créditos con garantía hipotecaria elevada a público ante el Notario de [Madrid/Barcelona], [Don/Dña] XXXXXXXX el pasado XX de XXXXXXXX de 2020, bajo el número XXXX de su protocolo,.
        /// </summary>
        public static string InformacionDelNotarioPlaceHolder {
            get {
                return ResourceManager.GetString("InformacionDelNotarioPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inversor.
        /// </summary>
        public static string Inversor {
            get {
                return ResourceManager.GetString("Inversor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localidad.
        /// </summary>
        public static string Localidad {
            get {
                return ResourceManager.GetString("Localidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar plantilla.
        /// </summary>
        public static string ModificarPlantilla {
            get {
                return ResourceManager.GetString("ModificarPlantilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre apoderado.
        /// </summary>
        public static string NombreApoderado {
            get {
                return ResourceManager.GetString("NombreApoderado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Originados.
        /// </summary>
        public static string Originados {
            get {
                return ResourceManager.GetString("Originados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portfolio.
        /// </summary>
        public static string Portfolio {
            get {
                return ResourceManager.GetString("Portfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quitas.
        /// </summary>
        public static string Quitas {
            get {
                return ResourceManager.GetString("Quitas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selección de variables.
        /// </summary>
        public static string SeleccionDeVariables {
            get {
                return ResourceManager.GetString("SeleccionDeVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sociedad.
        /// </summary>
        public static string Sociedad {
            get {
                return ResourceManager.GetString("Sociedad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtipo de certificado.
        /// </summary>
        public static string SubtipoDeCertificado {
            get {
                return ResourceManager.GetString("SubtipoDeCertificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texto.
        /// </summary>
        public static string Texto {
            get {
                return ResourceManager.GetString("Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texto pie de página.
        /// </summary>
        public static string TextoPieDePagina {
            get {
                return ResourceManager.GetString("TextoPieDePagina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ejemplo: Nº operación indicada corresponde con contrato original: XXXX-XXXX-XX-XXXXXXXXXXX (se informará para contratos migrados).
        /// </summary>
        public static string TextoPlaceHolder {
            get {
                return ResourceManager.GetString("TextoPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de certificado.
        /// </summary>
        public static string TipoDeCertificado {
            get {
                return ResourceManager.GetString("TipoDeCertificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título.
        /// </summary>
        public static string Titulo {
            get {
                return ResourceManager.GetString("Titulo", resourceCulture);
            }
        }
    }
}
