//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMaP.Resources.Pages.PortfolioRegistration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PortfolioRegistration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PortfolioRegistration() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PMaP.Resources.Pages.PortfolioRegistration.PortfolioRegistration", typeof(PortfolioRegistration).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualización cartera.
        /// </summary>
        public static string ActualizacionCartera {
            get {
                return ResourceManager.GetString("ActualizacionCartera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alta de la cartera.
        /// </summary>
        public static string AltaDeLaCartera {
            get {
                return ResourceManager.GetString("AltaDeLaCartera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargar.
        /// </summary>
        public static string Cargar {
            get {
                return ResourceManager.GetString("Cargar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conformación perímetros.
        /// </summary>
        public static string ConformacionPerimetros {
            get {
                return ResourceManager.GetString("ConformacionPerimetros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos básicos de la cartera.
        /// </summary>
        public static string DatosBasicosDeLaCartera {
            get {
                return ResourceManager.GetString("DatosBasicosDeLaCartera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examinar.
        /// </summary>
        public static string Examinar {
            get {
                return ResourceManager.GetString("Examinar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha alta.
        /// </summary>
        public static string FechaAlta {
            get {
                return ResourceManager.GetString("FechaAlta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herramientas de venta.
        /// </summary>
        public static string HerramientasDeVenta {
            get {
                return ResourceManager.GetString("HerramientasDeVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portfolio.
        /// </summary>
        public static string Portfolio {
            get {
                return ResourceManager.GetString("Portfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subporfolio.
        /// </summary>
        public static string Subporfolio {
            get {
                return ResourceManager.GetString("Subporfolio", resourceCulture);
            }
        }
    }
}
