//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMaP.Resources.Pages.PortfolioRegistration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PortfolioUpdate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PortfolioUpdate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PMaP.Resources.Pages.PortfolioRegistration.PortfolioUpdate", typeof(PortfolioUpdate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualización cartera.
        /// </summary>
        public static string ActualizacionCartera {
            get {
                return ResourceManager.GetString("ActualizacionCartera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualización datos del perímetro.
        /// </summary>
        public static string ActualizacionDatosDelPerimetro {
            get {
                return ResourceManager.GetString("ActualizacionDatosDelPerimetro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualización de fechas.
        /// </summary>
        public static string ActualizacionDeFechas {
            get {
                return ResourceManager.GetString("ActualizacionDeFechas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizar.
        /// </summary>
        public static string Actualizar {
            get {
                return ResourceManager.GetString("Actualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alta de la cartera.
        /// </summary>
        public static string AltaDeLaCartera {
            get {
                return ResourceManager.GetString("AltaDeLaCartera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string Cancelar {
            get {
                return ResourceManager.GetString("Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capital pendiente.
        /// </summary>
        public static string CapitalPendiente {
            get {
                return ResourceManager.GetString("CapitalPendiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capital vencido.
        /// </summary>
        public static string CapitalVencido {
            get {
                return ResourceManager.GetString("CapitalVencido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing.
        /// </summary>
        public static string Closing {
            get {
                return ResourceManager.GetString("Closing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conformación perímetros.
        /// </summary>
        public static string ConformacionPerimetros {
            get {
                return ResourceManager.GetString("ConformacionPerimetros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrato.
        /// </summary>
        public static string Contrato {
            get {
                return ResourceManager.GetString("Contrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut off.
        /// </summary>
        public static string CutOff {
            get {
                return ResourceManager.GetString("CutOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entidad de cesión.
        /// </summary>
        public static string EntidadDeCesion {
            get {
                return ResourceManager.GetString("EntidadDeCesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examinar.
        /// </summary>
        public static string Examinar {
            get {
                return ResourceManager.GetString("Examinar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha closing.
        /// </summary>
        public static string FechaClosing {
            get {
                return ResourceManager.GetString("FechaClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha cut off.
        /// </summary>
        public static string FechaCutOff {
            get {
                return ResourceManager.GetString("FechaCutOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha firma.
        /// </summary>
        public static string FechaFirma {
            get {
                return ResourceManager.GetString("FechaFirma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha primer imapago.
        /// </summary>
        public static string FechaPrimerImapago {
            get {
                return ResourceManager.GetString("FechaPrimerImapago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha signing.
        /// </summary>
        public static string FechaSigning {
            get {
                return ResourceManager.GetString("FechaSigning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha última extracción.
        /// </summary>
        public static string FechaUltimaExtraccion {
            get {
                return ResourceManager.GetString("FechaUltimaExtraccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha vencimiento.
        /// </summary>
        public static string FechaVencimiento {
            get {
                return ResourceManager.GetString("FechaVencimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herramientas de venta.
        /// </summary>
        public static string HerramientasDeVenta {
            get {
                return ResourceManager.GetString("HerramientasDeVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intereses de demora.
        /// </summary>
        public static string InteresesDeDemora {
            get {
                return ResourceManager.GetString("InteresesDeDemora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intereses ordinarios.
        /// </summary>
        public static string InteresesOrdinarios {
            get {
                return ResourceManager.GetString("InteresesOrdinarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº Fiadores.
        /// </summary>
        public static string NoFiadores {
            get {
                return ResourceManager.GetString("NoFiadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portfolio.
        /// </summary>
        public static string Portfolio {
            get {
                return ResourceManager.GetString("Portfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post-venta.
        /// </summary>
        public static string PostVenta {
            get {
                return ResourceManager.GetString("PostVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-venta.
        /// </summary>
        public static string PreVenta {
            get {
                return ResourceManager.GetString("PreVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saldo (OB).
        /// </summary>
        public static string SaldoOB {
            get {
                return ResourceManager.GetString("SaldoOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selección de la cartera.
        /// </summary>
        public static string SeleccionDeLaCartera {
            get {
                return ResourceManager.GetString("SeleccionDeLaCartera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing.
        /// </summary>
        public static string Signing {
            get {
                return ResourceManager.GetString("Signing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subporfolio.
        /// </summary>
        public static string Subporfolio {
            get {
                return ResourceManager.GetString("Subporfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titular.
        /// </summary>
        public static string Titular {
            get {
                return ResourceManager.GetString("Titular", resourceCulture);
            }
        }
    }
}
